# docker-compose up -d --build 

version: '3.8'

services:
  backend-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app # Mount the backend code
      - /var/run/docker.sock:/var/run/docker.sock # For Quantum users instances
    network_mode: "host"  # Use the host network for this service

  frontend-server:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3030:80" # Frontend's external port
    volumes:
      - ./client:/app # Mount the frontend code
